version: '3.3'

services:
  mysql-server:
    image: mysql:8.0.35
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=iPa*yrK3b*g7Cp43*i*uE7La
      - MYSQL_DATABASE=movies_db
      - MYSQL_USER=movies
      - MYSQL_PASSWORD=Gj4nU8nGC9XmcoIj!f03!C6x
    ports:
      - 33061:3306
    volumes:
      - movies-api-mysql-db-volume:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 200s
      retries: 10
  
  movies-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: movies-api:1.0
    restart: unless-stopped
    environment:
      - API_PORT=3000
      - DATABASE_HOST=mysql-server
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=movies
      - DATABASE_PASSWORD=Gj4nU8nGC9XmcoIj!f03!C6x
      - DATABASE_NAME=movies_db
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
      - DEFAULT_OPERATOR_EMAIL=admin@gmail.com
      - DEFAULT_OPERATOR_PASSWORD=Admin123!
    ports:
      - 3000:3000
    depends_on:
      mysql-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  movies-api-mysql-db-volume: